version: "3.3"
services:
  db_mongo:
    build: ./db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: dev_password
      MONGO_INITDB_DATABASE: hypertube
  api:
    build: ./api
    depends_on:
      - db_mongo
    environment:
      MONGO_URL: mongodb://db_mongo/hypertube
      SERVER_PORT: 3000
      API_URL: http://localhost:3000
      CLIENT_URL: http://localhost:4242
      CAPTCHA_KEY: 6LeSqisUAAAAAHl73wM2UnGn7yiNpyGMXL-4uBfL
      API_NODE_MAILER_KEY: ad85e70534aa0d9cca28c92b97183591-9dfbeecd-3ea3513c
      API_NODE_MAILER_DOMAIN: my42.fr
      API_THE_MOVIE_DB_KEY: 60d2c145d25e3e3e255301f028af6717
      API_YTS_KEY: 60d2c145d25e3e3e255301f028af6717
      API_GOOGLE_CONSUMER_KEY: 890991623460-ub2kv6vcjsg2emakj1ffngufpddhjhhq.apps.googleusercontent.com
      API_GOOGLE_CONSUMER_SECRET: FnguLYp8hFHK1LAiqD4Zmrml
      API_FACEBOOK_APP_ID: 529589211185864
      API_FACEBOOK_APP_SECRET: aabf36c45b05901f84ca390774d6fcf5
      API_FORTYTWO_APP_ID: 2de1c1df998f56f04be5a75d54c91efeb017a9824080537cfffbefbc32a5f9a5
      API_FORTYTWO_APP_SECRET: acdc14b0b7568724ebbf2a5978d63d0ca5dc47dd1d344a7c7d53262e7e2669a5
      API_GITHUB_CLIENT_ID: 9da4b03087a23460b89f
      API_GITHUB_CLIENT_SECRET: 59a8975e8c2562b4f473c3b33e9136c0e8934250
    ports:
      - "3000:3000"
    command: "yarn start"
  web_client:
    build: ./web
    depends_on:
      - api
    environment:
      PORT: 4242
      INTERNAL_CLIENT_API: http://api:3000
    ports:
      - "4242:4242"
    command: "yarn start"
