version: "3.3"
services:
  mongo:
    image: mongo:bionic
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: dev_password
      MONGO_INITDB_DATABASE: hypertube
    volumes:
      - ./server/config/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  api:
    image: node:12.10-alpine
    depends_on:
      - mongo
    working_dir: /app
    environment:
      MONGO_URL: mongodb://mongo/hypertube
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    command: /bin/sh -c "yarn && yarn dev.server"
