version: "3.3"
services:
  mongo:
    build: ./mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: dev_password
      MONGO_INITDB_DATABASE: hypertube
  server:
    build: ./server
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://mongo/hypertube
    ports:
      - "3000:3000"
    command: "yarn start"
